
"use client";

import { useState, useRef } from 'react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Download, Upload, Loader2, Image as ImageIcon, Plus, Trash2, Box, Layout, Code, AppWindow, ShieldCheck } from 'lucide-react';
import { ToolLayout } from '@/components/tools/tool-layout';
import { toast } from 'sonner';

const faviconSizes = [
    { size: 16, name: 'favicon-16x16.png' },
    { size: 32, name: 'favicon-32x32.png' },
    { size: 48, name: 'favicon.ico' },
    { size: 180, name: 'apple-touch-icon.png' },
    { size: 192, name: 'android-chrome-192x192.png' },
    { size: 512, name: 'android-chrome-512x512.png' },
];

export default function FaviconGeneratorClient() {
    const [sourceFile, setSourceFile] = useState<File | null>(null);
    const [previewUrl, setPreviewUrl] = useState<string | null>(null);
    const [isProcessing, setIsProcessing] = useState(false);
    const fileInputRef = useRef<HTMLInputElement>(null);

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            const file = e.target.files[0];
            if (!file.type.startsWith('image/')) {
                toast.error('Please select a valid image file.');
                return;
            }
            setSourceFile(file);
            setPreviewUrl(URL.createObjectURL(file));
        }
    };

    const generateFavicons = async () => {
        if (!sourceFile) return;
        setIsProcessing(true);

        const zip = new JSZip();
        const img = new Image();
        img.src = URL.createObjectURL(sourceFile);

        img.onload = async () => {
            try {
                for (const { size, name } of faviconSizes) {
                    const canvas = document.createElement('canvas');
                    canvas.width = size;
                    canvas.height = size;
                    const ctx = canvas.getContext('2d');
                    if (ctx) {
                        ctx.drawImage(img, 0, 0, size, size);
                        const blob = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, 'image/png'));
                        if (blob) {
                            zip.file(name, blob);
                        }
                    }
                }
                
                // manifest.json
                const manifest = {
                    name: "ESystemLk App",
                    short_name: "App",
                    icons: [
                        { src: "/android-chrome-192x192.png", sizes: "192x192", type: "image/png" },
                        { src: "/android-chrome-512x512.png", sizes: "512x512", type: "image/png" }
                    ],
                    theme_color: "#ffffff",
                    background_color: "#ffffff",
                    display: "standalone"
                };
                zip.file('site.webmanifest', JSON.stringify(manifest, null, 2));

                const htmlSnippet = `
<!-- Favicon Configuration -->
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="shortcut icon" href="/favicon.ico">
`;
                zip.file('README.txt', "Generated by ESystemLk Favicon Generator\n\nCopy this HTML to your <head> section:\n" + htmlSnippet);

                const zipBlob = await zip.generateAsync({ type: 'blob' });
                saveAs(zipBlob, 'esystemlk-favicons.zip');
                toast.success('Favicon package generated!');

            } catch (err) {
                toast.error('Failed to generate favicons.');
            } finally {
                setIsProcessing(false);
            }
        };
    };

    const clearInput = () => {
        setSourceFile(null);
        setPreviewUrl(null);
        if (fileInputRef.current) fileInputRef.current.value = '';
    };

    return (
        <ToolLayout 
            title="Premium Favicon Generator" 
            description="Create a professional set of favicons for all modern browsers and devices (Android, iOS, Desktop) from a single image. Instantly download a ready-to-use package."
            category="Design Tools"
        >
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
               {/* Controls */}
               <div className="lg:col-span-5 space-y-6">
                  <Card className="bg-white border border-gray-200 rounded-3xl shadow-sm overflow-hidden hover:border-[hsl(200,100%,50%,0.5)] hover:shadow-[0_0_20px_hsl(200,100%,50%,0.1)] transition-all flex flex-col">
                     <div className="h-1.5 bg-gradient-to-r from-primary via-primary/50 to-orange-500" />
                     <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                           <AppWindow className="w-5 h-5 text-primary" />
                           Source Image
                        </CardTitle>
                        <CardDescription>Upload a square logo for best results.</CardDescription>
                     </CardHeader>
                     <CardContent className="space-y-8 flex-grow">
                        <div className="relative group/upload">
                           {!previewUrl && (
                              <div 
                                 onClick={() => fileInputRef.current?.click()}
                                 className="h-48 border-2 border-dashed border-gray-200 rounded-2xl flex flex-col items-center justify-center cursor-pointer hover:bg-white/5 hover:border-primary/50 transition-all group-hover/upload:border-primary/30"
                              >
                                 <Plus className="w-12 h-12 text-primary/50 mb-3" />
                                 <p className="text-sm text-foreground/70 font-semibold tracking-wide uppercase">Select Master Logo</p>
                                 <p className="text-xs text-muted-foreground mt-1 underline">512x512 recommended</p>
                              </div>
                           )}
                           <input type="file" ref={fileInputRef} onChange={handleFileChange} className="hidden" accept="image/*" />

                           {previewUrl && (
                             <div className="relative rounded-2xl overflow-hidden bg-black/40 border border-gray-200 p-8 flex flex-col items-center">
                                <img src={previewUrl} alt="Preview" className="w-32 h-32 rounded-lg shadow-xl" />
                                <div className="mt-4 flex flex-col items-center gap-1">
                                   <p className="text-xs font-bold text-gray-400 truncate max-w-[200px] uppercase tracking-tighter">{sourceFile?.name}</p>
                                </div>
                                <Button variant="ghost" size="icon" onClick={clearInput} className="absolute top-2 right-2 h-8 w-8 text-red-400 hover:text-red-500 hover:bg-black/40 rounded-full">
                                   <Trash2 className="w-4 h-4" />
                                </Button>
                             </div>
                           )}
                        </div>

                        <div className="p-6 bg-white/5 rounded-2xl border border-gray-200 space-y-4">
                            <h4 className="text-xs font-black uppercase text-primary tracking-widest flex items-center gap-2">
                               <ShieldCheck className="w-4 h-4" /> Included in Package
                            </h4>
                            <div className="grid grid-cols-2 gap-y-3 text-[11px] font-bold text-gray-500">
                               <div className="flex items-center gap-2"><Layout className="w-3 h-3" /> 16x16 PNG</div>
                               <div className="flex items-center gap-2"><Layout className="w-3 h-3" /> 32x32 PNG</div>
                               <div className="flex items-center gap-2"><Box className="w-3 h-3" /> Android Chrome</div>
                               <div className="flex items-center gap-2"><Box className="w-3 h-3" /> Apple Touch Icon</div>
                               <div className="flex items-center gap-2"><Code className="w-3 h-3" /> Web Manifest</div>
                               <div className="flex items-center gap-2"><Code className="w-3 h-3" /> HTML Metadata</div>
                            </div>
                        </div>

                        <Button 
                           onClick={generateFavicons} 
                           disabled={!sourceFile || isProcessing} 
                           className="w-full h-14 bg-primary hover:bg-primary/90 text-lg font-black shadow-lg shadow-primary/20 transition-all"
                        >
                           {isProcessing ? <Loader2 className="w-5 h-5 animate-spin mr-2" /> : <Download className="w-5 h-5 mr-3" />}
                           {isProcessing ? 'PROCESSING...' : 'GENERATE FAVICONS'}
                        </Button>
                     </CardContent>
                  </Card>
               </div>

               {/* Preview */}
               <div className="lg:col-span-7 h-full">
                  <Card className="bg-white border border-gray-200 rounded-3xl shadow-sm overflow-hidden min-h-[600px] flex flex-col items-center justify-center relative p-12">
                     <div className="absolute top-6 left-6 flex items-center gap-2 text-[10px] font-black uppercase text-white/20 tracking-widest">
                        <Box className="w-3 h-3" /> Real-time Preview
                     </div>
                     
                     <div className="grid grid-cols-1 md:grid-cols-2 gap-12 w-full max-w-xl">
                        {/* Tab preview */}
                        <div className="space-y-4">
                           <p className="text-[10px] uppercase font-black text-center text-gray-400 tracking-widest">Web Browser Tab</p>
                           <div className="bg-black/60 rounded-xl p-4 border border-gray-200 flex items-center gap-3">
                              <div className="w-8 h-8 rounded bg-white/10 flex items-center justify-center p-1.5">
                                 {previewUrl ? <img src={previewUrl} className="w-full h-full object-contain" /> : <ImageIcon className="w-full h-full opacity-20" />}
                              </div>
                              <div className="h-4 w-24 bg-white/10 rounded-full" />
                           </div>
                        </div>

                        {/* Mobile preview */}
                        <div className="space-y-4">
                           <p className="text-[10px] uppercase font-black text-center text-gray-400 tracking-widest">Home Screen</p>
                           <div className="flex justify-center">
                              <div className="w-20 h-20 rounded-2xl bg-white/10 p-4 border-2 border-gray-200 flex items-center justify-center relative">
                                 {previewUrl ? <img src={previewUrl} className="w-full h-full object-contain rounded-xl" /> : <ImageIcon className="w-12 h-12 opacity-10" />}
                              </div>
                           </div>
                           <div className="h-2 w-16 bg-white/10 rounded-full mx-auto" />
                        </div>
                     </div>

                     <div className="mt-16 bg-blue-500/10 border border-blue-500/20 p-6 rounded-2xl max-w-lg">
                        <div className="flex gap-4 items-start">
                           <div className="bg-blue-500/20 p-2 rounded-lg"><Code className="w-4 h-4 text-blue-400" /></div>
                           <div className="text-xs text-blue-200/60 leading-relaxed">
                              <p className="font-black text-blue-400 mb-1 uppercase tracking-tighter">SEO & Accessibility Note</p>
                              Favicons are a crucial signal for browser usability and brand recognition. Having a complete set improves your site's professional appearance in Google search results and mobile home screens.
                           </div>
                        </div>
                     </div>
                  </Card>
               </div>
            </div>
        </ToolLayout>
    );
}


